server:
  port: 8080
spring: 
  application:
    name: accounts
  datasource:
    url: jdbc:mysql://localhost:3306/accountsdb
    username: root
    password: root
    sql: 
      init: 
        mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  config:
    import: "optional:configserver:http://localhost:8081/"
  profiles:
    active: "prod"
    build: 
  version: "3.0"

accounts: 
  message: "Welcome to Easybank accounts related local APIs"
  contactDetails: 
    name: "John Deo-Developer"
    email: "chaitragoudar62@gmail.com"
  onCallSupport: 
    - (555)555-1234
    - (555)523-1345
