spring:
  config:
    activate:
      on-profile:
      - "qa"
build: 
  version: "2.0"

accounts: 
  message: "Welcome to Easybank accounts related QA APIs"
  contactDetails: 
    name: "John Deo-QA-Developer"
    email: "chaitragoudar62@gmail.com"
  onCallSupport: 
    - (555)555-1234
    - (555)523-1345